### ISSUE TITLE
[managed-openshift/ROSA] Error installing CPD

### ISSUE THREAD

**Issue by chayan88** [IBM/cp4d-deployment#82] opened 2021-07-15 12:28 UTC
Hello Team,
Hope everyone is safe and well !!

I was trying to consume the `CP4D terraform asset` for managed `OpenShift on AWS (ROSA)` and got stuck in availability zone
The `vairable.tf ` has below variables for selecting `single_zone` or `multi_zone`
```
# Enter the number of availability zones the cluster is to be deployed, default is multi zone deployment.
variable "az" {
  description = "single_zone / multi_zone"
  default     = "multi_zone"
}
variable "availability_zone1" {
  description = "example eu-west-2a"
  default     = ""
}
variable "availability_zone2" {
  description = "example eu-west-2b"
  default     = ""
}
variable "availability_zone3" {
  description = "example eu-west-2c"
  default     = ""
}
```

If I switch to  single_zone and have a value only for  availability_zone1 variable terraform complains that

`E: Failed to create cluster: Only a single availability zone can be provided to a single-availability-zone cluster, instead received 2`

**Comment by akinfemi** [comment] 2021-07-21 19:10
hi @chayan88, could you post your redacted terraform logs? I was not able to reproduce the error from the information you provided.
In the logs there should be a line that shows the exact rosa command being executed. Something similar to this:
```bash
rosa create cluster --cluster-name='<cluster_name>' --compute-machine-type='m5.4xlarge' --compute-nodes 6 --region us-west-1   --machine-cidr='10.0.0.0/16' --service-cidr='172.30.0.0/16' --pod-cidr='10.128.0.0/14' --host-prefix='23' --private=false --multi-az=false --version='4.6.31' --subnet-ids='subnet-xxxxxxxxxx,subnet-xxxxxxxxxxxx' --watch"
```

**Comment by satyamodi** [comment] 2021-09-15 18:24
hi @chayan88, i was able to deploy single zone cluster with value only for availability_zone1. Can you pls try again and let me know if you still facing this issue.

**Comment by prsahoo** [comment] 2022-05-30 02:44
Closing the issue as it is too old now.  CPD installation is running fine now.  Please feel free to reopen if you encounter the issue again.  Thanks.

**Closed by prsahoo** 2022-05-30 02:44 UTC
