### ISSUE TITLE
Error on portworx instance not found during install

### ISSUE THREAD

**Issue by tcskill** [IBM/cp4d-deployment#100] opened 2022-04-15 00:09 UTC
Keep getting this while running the tf

Error: Error while removing volume attachment "0757-e8e9a0a9-3131-478e-9f06-54d452f510ef" for instance 0757_c74fb7bb-8aca-49ed-a071-a9f620eab1c6: "Instance not found"

**Comment by prsahoo** [comment] 2022-07-22 19:27
@tcskill   Are you still facing issue with Portworx Instance.  We have recently upgraded our scripts to install CPD 4.5.0.  Can you please give it a try and let us know if the issue is resolved.  In case it is not,  Can you please provide more details on 
1. Which environment you are trying to install Cloud Pak for Data on ?
2. Any logs from your installation that you could provide us for debugging purpose. 
Thank you.

**Comment by shankarpentyala07** [comment] 2023-05-16 16:14
Closing this issue , hoping the issue is no longer faced

**Closed by shankarpentyala07** 2023-05-16 16:14 UTC
