### ISSUE TITLE
Unable to Load the Notebook and Runtime Environments

### ISSUE THREAD

**Issue by Praveenmail2him** [IBM/cp4d-deployment#99] opened 2022-04-14 16:29 UTC
I'm facing this issue “Failed to Load the NoteBook”, in my CP4D. Kindly help.
I’m using Openshift 4.8.1 version and Cp4D 4.0 Version and Enabled WKC, Watson Studio Services. I’m unable to fetch any runtime environment.
My Openshift Pods are clean and showing no errors and nothing in pending or failure state.

**Comment by maulik-shah999** [comment] 2022-04-18 20:43
@Praveenmail2him We noticed this problem in the CPD `4.0.5` version. This issue will be fixed in the `4.0.7` CPD version. Our deployment script doesn't support the `4.0.7` version as of now.

**Comment by prsahoo** [comment] 2022-05-30 02:36
The issue is fixed.  Deploying a cluster using the latest code deploys CPD v4.0.5 and the loading of notebooks is fine.  @Praveenmail2him   Can you please retry whenever you get a chance and let us know if you still face any issues.   Thank you.

**Comment by prsahoo** [comment] 2022-07-22 19:22
Our scripts have been refreshed to CPD 4.5 and the issue is resolved.  Closing this issue.  Please reopen if you hit the issue again.

**Closed** 2022-07-22 19:23 UTC
